export type { ViewDocument, Background, BackgroundImage, Node, Connector, Widget, Binding, ValueMap, Shape, RectShape, TextShape, BoardAppearance } from './view-document.js';
export type { Adapter, AdapterReference, ConnectionQuality, QualityReason, ResolvedBinding, ResolvedWidget } from './adapter.js';
export { resolveWidget, applyValueMap } from './adapter.js';
export type { ResolvedNode, ResolvedViewDocument } from './resolve-document.js';
export { resolveDocument } from './resolve-document.js';
export { parseViewDocument, InvalidViewDocumentError } from './persistence/view-document-file.js';
export { validateViewDocument, isViewDocumentShape } from './validate-view-document.js';
export type { ViewDocumentIssue } from './validate-view-document.js';
export { QUALITY_LABEL, REASON_LABEL, DEFAULT_QUALITY_TEXT, ageText, worstQuality, describeQuality } from './quality-text.js';
export type { QualityText, QualitySummary, DescribeQualityOptions } from './quality-text.js';
