// The widget library's own text in Korean (a table's pagination, a region's name): with `locale` below,
// the widgets on a Korean board speak Korean too.
import '@iyulab/u-widgets/locales/ko';
import { timeText, type UBoardLabels } from './labels.js';
import { ageText } from './quality-text.js';

/** Every label in Korean — what `AuthoringView` and `ViewerPage` show when given `labels: KO_LABELS`,
 *  with times of day and ages in Korean too (`timeText('ko')`, `ageText('ko')`), and the widgets'
 *  own text and names in Korean. */
export const KO_LABELS: UBoardLabels = {
  locale: 'ko-KR',
  addNode: '노드 추가',
  addRectDecoration: '사각형 장식 추가',
  addTextDecoration: '텍스트 장식 추가',
  save: '저장',
  export: '내보내기',
  import: '가져오기',
  importFailed: '문서를 가져오지 못했습니다.',
  boardHeading: '보드',
  setBackground: '배경 이미지',
  removeBackground: '배경 제거',
  appearance: '바탕',
  appearanceLight: '밝게',
  appearanceDark: '어둡게',
  backgroundType: 'PNG, JPEG, WebP, GIF, SVG 이미지를 고르세요.',
  backgroundTooLarge: '이미지가 {max}보다 큽니다.',
  backgroundUnreadable: '이미지를 읽지 못했습니다.',

  zoomIn: '확대',
  zoomOut: '축소',
  fitToView: '화면에 맞추기',

  mode: '모드',
  editMode: '편집',
  viewMode: '보기',
  editorRegion: '편집기',
  previewRegion: '보드 보기',
  boardRegion: '보드',
  resolving: '불러오는 중…',
  lastUpdated: '갱신 {time}',
  notUpdating: '갱신이 멈춤 — 마지막 갱신 {time}',
  time: timeText('ko'),
  noDocument: '불러온 문서가 없습니다 — 가져오기로 여세요.',
  debugDocument: 'ViewDocument (디버그)',

  selectNode: '노드나 장식을 선택하면 여기서 편집합니다.',
  multipleSelected: '{count}개 선택됨 — 하나를 선택하면 편집할 수 있습니다.',
  propertiesHeading: '속성',
  widgetType: '위젯 타입',
  newNodeLabel: '새 노드',
  newNodeValue: '연결 전',
  staticProps: '정적 props (JSON)',
  widgetData: '데이터',
  widgetOptions: '표시',
  boundField: '바인딩됨',
  choiceDefault: '기본값',
  advancedProps: '고급: JSON으로 편집',
  moreInAdvanced: '고급에서 설정할 옵션: {count}개',
  invalidJson: '올바른 JSON이 아닙니다',
  bindingsHeading: '바인딩',
  noBindings: '바인딩 없음',
  editBinding: '수정',
  removeBinding: '제거',
  noDataSources: '연결된 데이터소스가 없습니다.',
  propPath: '프롭 경로',
  choosePropPath: '연결할 값을 고르세요',
  otherPropPath: '다른 경로…',
  typedPropPath: '위젯 props 안의 경로',
  dataSource: '데이터소스',
  reference: '참조',
  chooseReference: '참조를 고르세요',
  path: '요청 경로',
  keyInPath: '이 경로에 키가 들어 있는 것 같습니다. 보드는 경로를 그대로 저장하고 공유 링크는 그것을 보여 줍니다 — 키는 데이터소스의 인증 방식으로 보내세요.',
  valuePath: '값 경로',
  explore: '탐색',
  exploreFailed: '탐색에 실패했습니다',
  wholeResponse: '(전체 응답)',
  previewBinding: '미리보기',
  previewFailed: '미리보기 호출에 실패했습니다',
  saveBinding: '바인딩 저장',
  bindingNeedsPropPath: '연결할 프롭 경로를 입력하세요.',
  bindingNeedsReference: '참조를 고르세요.',
  valueMapHeading: '값 매핑',
  mapFrom: '원천 값 {n}',
  mapTo: '표시 값 {n}',
  addMapping: '매핑 추가',
  removeMapping: '매핑 {n} 삭제',
  rangeMin: '구간 {n} 이상',
  rangeMax: '구간 {n} 미만',
  rangeTo: '구간 {n} 표시 값',
  addRange: '구간 추가',
  removeRange: '구간 {n} 삭제',
  rangeInvalid: '구간 {n}: 이상·미만 중 하나 이상을 적고, 둘 다 적으면 미만이 더 커야 합니다.',
  mapOtherwise: '그 밖의 값',
  mapOtherwisePlaceholder: '받은 그대로',
  mapped: '매핑됨',
  previewValue: '값',
  previewLive: '정상',

  decorationHeading: '장식',
  decorationText: '라벨',
  decorationHint: '캔버스에서 드래그/리사이즈로 위치와 크기를 조정하세요.',
  newTextDecoration: '라벨',

  qualityText: {
    quality: {
      stale: '갱신 지연 — 마지막으로 받은 값을 표시 중',
      disconnected: '연결 끊김 — 값을 받지 못함',
    },
    reason: {
      transport: '데이터소스에 연결할 수 없음',
      auth: '자격 증명이 거부됨',
      address: '바인딩한 값이 원천에 없음',
      throttled: '요청 한도 초과',
    },
    age: ageText('ko'),
  },
};
